# Generated by Django 6.0.5 on 2026-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('pants', 'Pants'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('belts', 'Belts')], max_length=50)),
                ('image_url', models.URLField()),
                ('public_id', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
